# vm для тестов
Vagrant.configure("2") do |config|
    config.vm.define "test-vm" do |node|  
      node.vm.box = "ubuntu/jammy64"
    
      node.vm.network "public_network", ip: "192.168.1.228"
    
      node.vm.provider "virtualbox" do |vb|
        vb.name = "yadro-test-vm"
        vb.memory = "2048"
        vb.cpus = 2
      end
    
      node.vm.hostname = "test-vm"  
  
      node.vm.provision "shell", inline: <<-SHELL
        apt-get update -y
        apt-get install -y python3 python3-pip
      SHELL
    end
  end